### ISSUE TITLE
Does Module Federation work with this?

### ISSUE THREAD

**Issue by vijaybritto** [efoxTeam/snowpack-mf#1]
Hi,

I think this plugin was created specifically to test module federation capability in webpack 5. Did this work?

**Comment by ckken** [comment]
@flyyuan

**Comment by flyyuan** [comment]
Are you referring to snowpack-mf?  If it is, it is used by us to try module federation on snowpack, not to test compatibility with webpack5.

**Comment by vijaybritto** [comment]
Yes thats what I'm referring to. Is Module federation working with snowpack?


Thanks,

Vijay

________________________________

**Comment by flyyuan** [comment]
Yes, the code is implemented using aliases.
